# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-10 15:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_ticket_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='issue_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
