# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-10 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190810_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='author',
        ),
    ]
