# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-22 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190822_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='author',
        ),
    ]
